version: "3"

services:

  app:
    container_name: app
    tty: true
    build:
      dockerfile: ./.docker/php/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./example-app:/var/www/html/app
    working_dir: /var/www/html/app
    networks:
      - laravel_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  laravel_net:
    driver: bridge